### PR TITLE
fix: short names were used as SeverityText instead of log level name

### LINKED ISSUE #153: BUG: Short names as SeverityText
It took me some digging to track this down, as I was wondering why there was an enum defined for SeverityNumber but not for SeverityText. Looking through the defined types, SeverityText can be [any string](https://github.com/open-telemetry/opentelemetry-js/blob/63d74cdc366fc337be66c1a766a2cc8e5275a85a/experimental/packages/api-logs/src/types/LogRecord.ts#L71)

From the [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/8a78903ef0a1fe7a2056ae4c8c45f9ef10ae9e78/specification/logs/data-model.md#field-severitytext):

> Description: severity text (also known as log level). This is the original string representation of the severity as it is known at the source. If this field is missing and SeverityNumber is present then the _short name_ that corresponds to the SeverityNumber may be used as a substitution. This field is _optional_.

(emphasis added)

It later gives the example:

> For example "Informational" Syslog record will be displayed as INFO (Informational). When for a particular log record the SeverityNumber is defined but the SeverityText is missing it is recommended to only show the short name, e.g. INFO.

So here, Informational appears to be the SeverityText and INFO is the short name.

With this in mind, using a map to retrieve the short name for a given SeverityNumber as the SeverityText seems to not be the intended use of SeverityText. This should likely be configurable.

Using the short names as SeverityText is perfectly fine for my use case right now, and I could be mistaken in my interpretation, but I wanted to flag this for you.

### PR DESCRIPTION
**Pull request by 10xLaCroixDrinker**
Fixes #153

### CODE REVIEW

**Comment by 10xLaCroixDrinker** [comment]
@Vunovati I'm going to work on a change in pino to get access to log levels directly from transports so we can implement this without expanding the API. This can go on hold until then.

**Comment by Vunovati** [comment]
> @Vunovati I'm going to work on a change in pino to get access to log levels directly from transports so we can implement this without expanding the API. This can go on hold until then.

OK, I hope Pino will be open to this change. Could you also reference the Pino issue/PR when there is one?

**Comment by 10xLaCroixDrinker** [comment]
Just a status update FYA @Vunovati, they're aligned with the approach, and two of the three PRs are approved now.

**Comment by 10xLaCroixDrinker** [comment]
Superseded by #165

**Pull request closed without merging**
